---
    
- hosts: node1
  vars:
    newname: 
    - 0013node1
    
  tasks:

  - name: set hostname
    shell: "hostname {{ newname[0] }} && sed -i 's/vultr/{{ newname[0] }}/g' /etc/hosts && echo {{ newname[0] }} > /etc/hostname"
    args:
      executable: /bin/ash
    tags: 
      - hostname
      - install
...

---
    
- hosts: node3
  vars:
    newname: 
    - 0013node2
    
  tasks:

  - name: set hostname
    shell: "hostname {{ newname[1] }} && sed -i 's/vultr/{{ newname[1] }}/g' /etc/hosts && echo {{ newname[1] }} > /etc/hostname"
    args:
      executable: /bin/ash
    tags: 
      - hostname
      - install
...

---
    
- hosts: node3
  vars:
    newname: 
    - 1113node3
    
  tasks:

  - name: set hostname
    shell: "hostname {{ newname[2] }} && sed -i 's/vultr/{{ newname[2] }}/g' /etc/hosts && echo {{ newname[2] }} > /etc/hostname"
    args:
      executable: /bin/ash
    tags: 
      - hostname
      - install
...

---

- hosts: rocky   
  tasks:
      
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
    tags:
      - upgrade
      - patch

  - name: install aide
    yum:
      name: 'aide'
      state: latest
    tags:
      - upgrade
      - aide
      - install

  - name: install clamav
    yum:
      name: 'clamav'
      state: latest
    tags:
      - upgrade
      - clamav
      - install

  - name: install clamav-update
    yum:
      name: 'clamav-update'
      state: latest
    tags:
      - upgrade
      - clamav
      - install

  - name: run a freshclam
    shell: freshclam
      executable: /bin/sh
    tags:
      - clamav
      - install
      
  - name: initialize aide
    shell: aide --init
      executable: /bin/sh
    tags:
      - aide
      - install

  - name: set motd
    copy:
      src: files/motd
      dest: /etc/motd
    tags: 
      - motd
      - install
      
  - name: deploy monolith
    copy:
      src: files/monolith
      dest: /usr/local/sbin/
    tags: 
      - install
      - monolith
      - deploy

  - name: deploy monolith systemd unit file
    copy:
      src: files/monolith.service
      dest: /etc/systemd/system/monolith.service
    tags: 
      - install
      - monolith
      - deploy   

  - name: initialize the monolith
    shell: systemctl enable monolith && systemctl start monolith
      executable: /bin/sh
    tags:
      - monolith
      - deploy

  - name: monolith firewall rules
    shell: "firewall-cmd --zone=public --permanent --add-port=7443/tcp && firewall-cmd reload"
      executable: /bin/sh
    tags:
      - monolith
      - deploy      
...
