---
    
- hosts: node1
  vars:
    newname: 
    - 0013node1
    
  tasks:

  - name: set hostname
    shell: "hostname {{ newname[0] }} && sed -i 's/vultr/{{ newname[0] }}/g' /etc/hosts && echo {{ newname[0] }} > /etc/hostname"
    args:
      executable: /bin/ash
    tags: 
      - hostname
      - install
    
- hosts: node2
  vars:
    newname: 
    - 0013node2
    
  tasks:

  - name: set hostname
    shell: "hostname {{ newname[1] }} && sed -i 's/vultr/{{ newname[1] }}/g' /etc/hosts && echo {{ newname[1] }} > /etc/hostname"
    args:
      executable: /bin/ash
    tags: 
      - hostname
      - install
    
- hosts: node3
  vars:
    newname: 
    - 1113node3
    
  tasks:

  - name: set hostname
    shell: "hostname {{ newname[2] }} && sed -i 's/vultr/{{ newname[2] }}/g' /etc/hosts && echo {{ newname[2] }} > /etc/hostname"
    args:
      executable: /bin/ash
    tags: 
      - hostname
      - install

- hosts: rocky   
  tasks:
      
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
    tags:
      - upgrade
      - patch

  - name: install aide
    yum:
      name: 'aide'
      state: latest
    tags:
      - upgrade
      - aide
      - install

  - name: install clamav
    yum:
      name: 'clamav'
      state: latest
    tags:
      - upgrade
      - clamav
      - install

  - name: install clamav-update
    yum:
      name: 'clamav-update'
      state: latest
    tags:
      - upgrade
      - clamav
      - install

  - name: run a freshclam
    shell: freshclam
      executable: /bin/sh
    tags:
      - clamav
      - install
      
  - name: initialize aide
    shell: aide --init
      executable: /bin/sh
    tags:
      - aide
      - install
      
  - name: make directories
    shell: mkdir -p /opt/monolith/etc /etc/monolith
      executable: /bin/sh
    tags:
      - monolith
      - deploy
      
  - name: set motd
    copy:
      src: files/motd
      dest: /etc/motd
    tags: 
      - motd
      - install

  - name: set pki_env
    copy:
      src: files/pki_env
      dest: /etc/monolith/pki_env
    tags: 
      - monolith
      - install 
      
  - name: deploy identity.p12
    copy:
      src: files/identity.p12
      dest: /opt/monolith/etc/identity.p12
    tags: 
      - monolith
      - install
      
  - name: deploy monolith
    copy:
      src: files/monolith
      dest: /usr/local/sbin/
    tags: 
      - install
      - monolith
      - deploy

  - name: deploy monolith systemd unit file
    copy:
      src: files/monolith.service
      dest: /etc/systemd/system/monolith.service
    tags: 
      - install
      - monolith
      - deploy   

  - name: tighten DAC for monolith files
    shell: "chown root:root /opt/monolith/etc/identity.p12 /etc/monolith/pki_env && chmod 0600 /opt/monolith/etc/identity.p12 /etc/monolith/pki_env"
      executable: /bin/sh
    tags:
      - monolith
      - deploy 

  - name: initialize the monolith
    shell: chmod +x /usr/local/sbin/monolith && systemctl enable monolith && systemctl start monolith
      executable: /bin/sh
    tags:
      - monolith
      - deploy

  - name: create selinux module for monolith on the fly
    shell: "ausearch -c '(monolith)' --raw | audit2allow -M my-monolith && semodule -i my-monolith.pp && /sbin/restorecon -v /usr/local/sbin/monolith"
      executable: /bin/sh
    tags:
      - monolith
      - deploy
      - selinux

  - name: restart monolith
    shell: systemctl restart monolith
      executable: /bin/sh
    tags:
      - monolith
      - apprestart
      - deploy

  - name: monolith firewall rules
    shell: "firewall-cmd --zone=public --permanent --add-port=7443/tcp && firewall-cmd reload"
      executable: /bin/sh
    tags:
      - monolith
      - deploy  
   
...
